--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsMax123/KOTH
build-by-default: true
branches:
- master
projects:
  KOTH:
    path: ""
    icon: "koth.png"
    libs:
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.2
        branch: PM4
      - src: CortexPE/Commando/Commando
        version: 2.1.1
        branch: PM4
      - src: thebigsmilexd/apibossbar/apibossbar
        version: 0.1.5
        branch: PM4
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: 0.1.0
    lint:
      phpstan: false
...
